"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { request, CORE_API_BASE, type Asset } from "@/lib/core-api";

type Model = { revision: string; name: string; kind: string; archived: number };
type Connection = { id: string; name: string; provider: string; enabled: number };
type Personality = { id: string; name: string; voice: string; rate: number };
type Script = { id: string; name: string; source: string; sha256: string; run_id: string | null };
type Inventory = { models: Model[]; connections: Connection[]; scripts: Script[]; personalities: Personality[]; installed_voices: string[]; asr_available: boolean };
type Dataset = { id: string; name: string; revision: number };
type Output = { id: string; filename: string; operation: string; artifacts: {name:string; mime:string}[] };
const post = <T,>(path: string, value: unknown) => request<T>(path, { method: "POST", body: JSON.stringify(value) });

export default function Integrations({ projectId, view, assets }: { projectId: string; view: string; assets: Asset[] }) {
  const [inventory, setInventory] = useState<Inventory>({models:[],connections:[],scripts:[],personalities:[],installed_voices:[],asr_available:false});
  const [selected, setSelected] = useState<string[]>([]), [labels, setLabels] = useState<Record<string,string>>({});
  const [name, setName] = useState("My local model"), [kind, setKind] = useState("tfidf"), [model, setModel] = useState("");
  const [query, setQuery] = useState(""), [result, setResult] = useState<unknown>(null), [notice, setNotice] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [connectionName, setConnectionName] = useState("Hugging Face"), [secret, setSecret] = useState(""), [connection, setConnection] = useState(""), [remote, setRemote] = useState(false), [remoteDataset, setRemoteDataset] = useState(""), [remoteRevision, setRemoteRevision] = useState("");
  const [source, setSource] = useState('data = fill_missing(data, columns=["income"], strategy="mean")'), [scriptName, setScriptName] = useState("My workflow"), [datasets, setDatasets] = useState<Dataset[]>([]), [dataset, setDataset] = useState("");
  const [voice, setVoice] = useState(""), [voiceName, setVoiceName] = useState("Narrator"), [rate, setRate] = useState(0), [personality, setPersonality] = useState(""), [speechAsset, setSpeechAsset] = useState(""), [audioAsset, setAudioAsset] = useState(""), [outputs, setOutputs] = useState<Output[]>([]);
  const base = `/integrations/projects/${projectId}`;
  const documents = assets.filter(asset => asset.media_type === "document" && asset.state === "active");
  async function refresh() {
    const [next, tables, saved] = await Promise.all([request<Inventory>(base), request<{items:Dataset[]}>(`/lab/projects/${projectId}/datasets`), request<{items:Output[]}>(`/lab/projects/${projectId}/asset-outputs`)]);
    setInventory(next); setDatasets(tables.items); setOutputs(saved.items);
  }
  useEffect(() => { let live=true; request<Inventory>(base).then(value=>{if(live)setInventory(value)}).catch(e=>{if(live)setError(String(e))}); request<{items:Dataset[]}>(`/lab/projects/${projectId}/datasets`).then(value=>{if(live)setDatasets(value.items)}).catch(e=>{if(live)setError(String(e))}); return()=>{live=false}; },[base,projectId]);
  async function act(fn:()=>Promise<unknown>, message:string) {
    setBusy(true);setError("");setNotice("");
    try { const value=await fn();setResult(value);setNotice(message);await refresh(); }
    catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}
  }
  const queue=(operation:string,ids:string[],parameters:Record<string,unknown>)=>post(`/lab/projects/${projectId}/asset-operations`,{operation,asset_ids:ids,parameters});
  const selectedModel=inventory.models.find(item=>item.revision===model);
  return <section className="data-lab integration-lab">
    <div className="lab-toolbar"><h1>{view}</h1><Button disabled={busy} onClick={()=>void act(refresh,"Integration state refreshed.")}>Refresh integrations</Button></div>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {view==="Model Hub"&&<>
      <div className="batch-columns"><section className="lab-panel"><h2>Train from indexed documents</h2><p>Fit a local lexical retrieval model or a supervised language classifier. Training saves an immutable revision and its source hashes.</p>
        <label>Model name<Input aria-label="Model name" value={name} onChange={e=>setName(e.target.value)}/></label>
        <label>Model kind<select aria-label="Model kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="tfidf">Fitted TF-IDF retrieval</option><option value="language">Supervised language classifier</option></select></label>
        {documents.map(asset=><div key={asset.id}><label className="lab-check"><input type="checkbox" checked={selected.includes(asset.id)} onChange={e=>setSelected(e.target.checked?[...selected,asset.id]:selected.filter(id=>id!==asset.id))}/>{asset.original_filename}</label>{kind==="language"&&selected.includes(asset.id)&&<Input aria-label={`Language label ${asset.original_filename}`} placeholder="en, ur, fr…" value={labels[asset.id]??""} onChange={e=>setLabels({...labels,[asset.id]:e.target.value})}/>}</div>)}
        {!documents.length&&<p>Import and prepare documents in Knowledge Lab first.</p>}
        <Button disabled={busy||!selected.length} onClick={()=>void act(()=>post(`${base}/models/train`,{name,kind,asset_ids:selected,labels,confirmed:true}),"Training queued. Follow Jobs, then refresh integrations.")}>Train locally</Button>
        <label>Import fitted model JSON<Input aria-label="Import fitted model JSON" type="file" accept=".json" onChange={e=>{const file=e.target.files?.[0];if(file)void act(async()=>{if(file.size>4*1024*1024)throw Error("Model exceeds 4 MiB");return post('/integrations/models/import',JSON.parse(await file.text()))},"Model revision imported and verified.");e.target.value=""}}/></label>
      </section><section className="lab-panel"><h2>Model revisions</h2>
        <label>Selected model<select aria-label="Selected model" value={model} onChange={e=>setModel(e.target.value)}><option value="">Select an exact revision</option>{inventory.models.map(item=><option key={item.revision} value={item.revision}>{item.name} · {item.kind} · {item.revision.slice(0,12)}{item.archived?" · archived":""}</option>)}</select></label>
        {selectedModel&&<><p className="integration-hash">SHA-256: {model}</p><div className="lab-toolbar"><Button disabled={busy} onClick={()=>void act(()=>request(`/integrations/models/${model}`),"Revision checksum verified.")}>Verify revision</Button><a href={`${CORE_API_BASE}/integrations/models/${model}/download`}>Download model JSON</a><Button disabled={busy} onClick={()=>void act(()=>post(`/integrations/models/${model}/archive`,{archived:!selectedModel.archived}),selectedModel.archived?"Model reactivated.":"Model archived; existing provenance remains available.")}>{selectedModel.archived?"Reactivate model":"Archive model"}</Button></div>
        {selectedModel.kind==="tfidf"&&<Button disabled={busy||!selected.length||Boolean(selectedModel.archived)} onClick={()=>void act(()=>queue("document.embed",selected,{model_revision:model}),"Pinned indexing queued. Refresh after Jobs completes.")}>Index selected documents</Button>}
        <label>{selectedModel.kind==="tfidf"?"Retrieval query":"Text to classify"}<Textarea aria-label="Model query" value={query} onChange={e=>setQuery(e.target.value)}/></label><Button disabled={busy||!query.trim()} onClick={()=>void act(()=>post(selectedModel.kind==="tfidf"?`${base}/search`:'/integrations/language',{revision:model,text:query}),"Model query completed.")}>Run model query</Button></>}
      </section></div></>}
    {view==="Connections"&&<div className="batch-columns"><section className="lab-panel"><h2>Save a connection</h2><p>Tokens are stored in your native OS credential store. The workspace retains only the connection name and provider.</p><label>Connection name<Input aria-label="Connection name" value={connectionName} onChange={e=>setConnectionName(e.target.value)}/></label><label>Hugging Face token<Input aria-label="Hugging Face token" type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)}/></label><Button disabled={busy||!secret} onClick={()=>void act(async()=>{const token=secret;setSecret("");return post('/integrations/connections',{name:connectionName,provider:'huggingface',secret:token})},"Credential saved to the OS store.")}>Save connection</Button>
      {inventory.connections.map(item=><div className="lab-toolbar" key={item.id}><span>{item.name} · {item.enabled?"enabled":"revoked"}</span>{Boolean(item.enabled)&&<Button disabled={busy} onClick={()=>void act(()=>post(`/integrations/connections/${item.id}/revoke`,{}),"Connection revoked and credential removed.")}>Revoke {item.name}</Button>}</div>)}
      <p>Existing plugin trust approvals, compatibility checks and reload controls remain in System.</p></section><section className="lab-panel"><h2>Import a provider dataset</h2><label>Connection<select aria-label="Saved connection" value={connection} onChange={e=>setConnection(e.target.value)}><option value="">Select a connection</option>{inventory.connections.filter(item=>item.enabled).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Dataset<Input aria-label="Provider dataset" placeholder="owner/dataset" value={remoteDataset} onChange={e=>setRemoteDataset(e.target.value)}/></label><label>Revision<Input aria-label="Provider revision" placeholder="Optional revision" value={remoteRevision} onChange={e=>setRemoteRevision(e.target.value)}/></label><p>Requires an approved external project. Limits: 100 files, 100 MiB per file, 512 MiB total.</p><label className="lab-check"><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/>I authorize this remote dataset import</label><Button disabled={busy||!remote||!connection||!remoteDataset} onClick={()=>void act(()=>post(`${base}/imports`,{connection,dataset:remoteDataset,revision:remoteRevision||null,allow_remote:remote}),"Provider import queued. Jobs retains progress and errors.")}>Queue provider import</Button></section></div>}
    {view==="Playground"&&<div className="batch-columns"><section className="lab-panel"><h2>Operation script</h2><p>Use <code>data = operation(data, parameter=value)</code>. The script compiles to the shared workflow engine. Imports, loops and arbitrary Python are unavailable.</p><label>Script name<Input aria-label="Script name" value={scriptName} onChange={e=>setScriptName(e.target.value)}/></label><label>Python operation calls<Textarea aria-label="Playground source" rows={10} spellCheck={false} value={source} onChange={e=>setSource(e.target.value)}/></label><label>Working dataset<select aria-label="Playground dataset" value={dataset} onChange={e=>setDataset(e.target.value)}><option value="">Select a working dataset</option>{datasets.map(item=><option key={item.id} value={item.id}>{item.name} · revision {item.revision}</option>)}</select></label><div className="lab-toolbar"><Button disabled={busy} onClick={()=>void act(()=>post(`${base}/playground`,{name:scriptName,source}),"Script validated and saved. Review compiled steps below.")}>Validate and save</Button><Button disabled={busy||!dataset} onClick={()=>void act(()=>post(`${base}/playground`,{name:scriptName,source,dataset,revision:datasets.find(item=>item.id===dataset)?.revision,execute:true}),"Workflow queued. Results and versions appear in Data Lab and Jobs.")}>Run script</Button></div></section><section className="lab-panel"><h2>Saved scripts</h2>{inventory.scripts.map(item=><div key={item.id} className="lab-panel"><Button onClick={()=>{setSource(item.source);setScriptName(item.name)}}>{item.name}</Button><p className="integration-hash">{item.sha256}</p><p>{item.run_id?`Run ${item.run_id}`:"Validated without execution"}</p></div>)}</section></div>}
    {view==="Voices"&&<><div className="batch-columns"><section className="lab-panel"><h2>Local voice personalities</h2><label>Personality name<Input aria-label="Personality name" value={voiceName} onChange={e=>setVoiceName(e.target.value)}/></label><label>Installed voice<select aria-label="Installed voice" value={voice} onChange={e=>setVoice(e.target.value)}><option value="">Select a local voice</option>{inventory.installed_voices.map(item=><option key={item}>{item}</option>)}</select></label><label>Speaking rate<Input aria-label="Speaking rate" type="number" min={-10} max={10} value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><Button disabled={busy||!voice} onClick={()=>void act(()=>post('/integrations/voices',{name:voiceName,voice,rate}),"Voice personality saved.")}>Save personality</Button><label>Saved personality<select aria-label="Saved personality" value={personality} onChange={e=>setPersonality(e.target.value)}><option value="">Select personality</option>{inventory.personalities.map(item=><option value={item.id} key={item.id}>{item.name} · {item.voice}</option>)}</select></label><label>Document to speak<select aria-label="Speech document" value={speechAsset} onChange={e=>setSpeechAsset(e.target.value)}><option value="">Select a document (up to 5000 characters)</option>{documents.map(item=><option key={item.id} value={item.id}>{item.original_filename}</option>)}</select></label><Button disabled={busy||!personality||!speechAsset} onClick={()=>void act(()=>queue('document.speak',[speechAsset],{personality}),"Speech queued. Refresh after the worker completes.")}>Generate speech</Button>{!inventory.installed_voices.length&&<p>The Windows speech adapter needs an installed system voice.</p>}</section>
      <section className="lab-panel"><h2>Local transcription</h2><p>{inventory.asr_available?"Local whisper.cpp and a model are configured.":"Set MEDIASENSEI_WHISPER_CPP and MEDIASENSEI_WHISPER_MODEL before starting the app. Models are never downloaded automatically."}</p><label>Audio to transcribe<select aria-label="Transcription audio" value={audioAsset} onChange={e=>setAudioAsset(e.target.value)}><option value="">Select an audio asset</option>{assets.filter(item=>item.media_type==='audio'&&item.state==='active').map(item=><option key={item.id} value={item.id}>{item.original_filename}</option>)}</select></label><p>Processes at most the first 60 seconds using two CPU threads.</p><Button disabled={busy||!inventory.asr_available||!audioAsset} onClick={()=>void act(()=>queue('audio.transcribe',[audioAsset],{}),"Transcription queued. Results appear below and in Audio Lab outputs.")}>Transcribe locally</Button></section></div>
      <section className="lab-panel"><h2>Speech and transcription outputs</h2>{outputs.filter(item=>['document.speak','audio.transcribe'].includes(item.operation)).map(item=><div key={item.id}><p>{item.filename} · {item.operation}</p>{item.artifacts.map((artifact,index)=>artifact.mime.startsWith('audio/')?<audio key={index} controls preload="metadata" src={`${CORE_API_BASE}/lab/asset-outputs/${item.id}/artifacts/${index}`}/>:<a key={index} href={`${CORE_API_BASE}/lab/asset-outputs/${item.id}/artifacts/${index}`}>{artifact.name}</a>)}<a href={`${CORE_API_BASE}/lab/asset-outputs/${item.id}/download`}>Download output and provenance</a></div>)}</section></>}
    {result!==null&&<details open={view==="Playground"} className="lab-panel"><summary>Result / compiled plan</summary><pre className="lab-json">{JSON.stringify(result,null,2)}</pre></details>}
  </section>;
}
